SICA Time Comparison- Results Analysis

Step 1: Import relevant state functions and packages

In [3]:
from EditedCode.genetic.state import CurrentState as st0
from cax_sica.genetic.state import CurrentState as st2
from cax_sica_decomp.genetic.state import CurrentState as st1

import numpy as np
import time

Step 2: Create the IC and SRT

In [40]:
starttime = time.time()

def generateicsrt(dim, num_steps, example = 0):
    ic = np.random.choice([0,0,0,1], size=(dim, dim))
    srt = np.random.choice([0,0,0,0,0,1], size=(num_steps, dim, dim, 18))
    if (example == 1):
        ic = np.random.choice([0,0,1], size=(dim, dim))
        srt = np.full((num_steps, dim, dim, 18), [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0])
    srtcomp = np.zeros((num_steps, dim, dim, 18, 4))
    for i in range(num_steps):
        for j in range(dim):
            for k in range(dim):
                for l in range(18):
                    srtcomp[i][j][k][l] = np.array([8-l%9, l%9, int(np.floor(l/9)), srt[i][j][k][l]])
    return ic, srt, srtcomp
#100, 100 takes about 47-49s to generate. The time increases ^2 with respect to dim and ^1 with respect to num_steps.
stepdim = [10,100,0]
icsrtcomp = generateicsrt(stepdim[0], stepdim[1], stepdim[2])
ic = icsrtcomp[0]
srt = icsrtcomp[1]
srtcomp = icsrtcomp[2]

print(time.time() - starttime)


0.4790325164794922


Step 3: Simulate Original Code

In [41]:
starttime = time.time()
state = st0(initial=ic, rules=srtcomp)
st0res = state.generate()
print(time.time() - starttime)


0.1987154483795166


Step 4: Simulate Attempt 1 Code (SICA Decomposition)

In [42]:
starttime = time.time()
state = st1(initial=ic, rules=srtcomp)
st1res = state.generate()
print(time.time() - starttime)


489.0211338996887


Step 5: Simulate Attempt 2 Code (SICA System)

In [38]:
starttime = time.time()
state = st2(initial=ic, rules=srt)
st2res = state.generate()
print(time.time() - starttime)


0.22713828086853027


Step 6: Ensure all results are correct

In [39]:
print(f"Dims: {stepdim[0]}x{stepdim[0]}, Timesteps: {stepdim[1]}")
print("\n")
print(f"Orig = Att 2: {np.all(st0res == st2res)}")
print(f"Orig = Att 1: {np.all(st0res == st1res)}")
print(f"Att 1 = Att 2: {np.all(st1res == st2res)}")

print(st2res)



Dims: 10x10, Timesteps: 50


Orig = Att 2: True
Orig = Att 1: True
Att 1 = Att 2: True
[[[0 1 1 ... 1 1 0]
  [0 0 0 ... 1 0 0]
  [0 0 1 ... 1 0 0]
  ...
  [0 1 0 ... 0 1 0]
  [0 0 1 ... 0 0 0]
  [1 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 1 0 ... 1 0 1]
  [0 0 0 ... 1 0 1]
  ...
  [1 0 1 ... 0 1 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 1 0]]

 [[0 0 0 ... 1 1 1]
  [0 1 0 ... 1 0 0]
  [0 0 0 ... 1 0 1]
  ...
  [0 0 0 ... 1 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 1]]

 ...

 [[0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 1]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 1 1]
  [0 0 1 ... 0 0 1]]

 [[0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 1 1 ... 0 1 1]
  ...
  [0 0 0 ... 0 1 0]
  [0 0 0 ... 0 0 1]
  [0 0 0 ... 1 0 0]]

 [[0 0 0 ... 1 0 0]
  [0 0 0 ... 0 0 0]
  [0 1 0 ... 1 1 0]
  ...
  [0 0 0 ... 0 1 0]
  [1 0 0 ... 1 0 0]
  [0 0 0 ... 1 0 0]]]
