In [14]:
#%pip install -U "jax[cuda12]"
#%pip install -U "cax"
import jax
import jax.numpy as jnp
from flax import nnx
from cax_new.systems.sica import sica
"""Testcase for transition.py."""

def transition(ic, srt, steps, strict = False):

	seed = 0
	num_steps = steps
	time = 0
	rngs = nnx.Rngs(seed)

	ca = sica(rngs=rngs)
	state_init = jnp.zeros((ic.shape[0]+2, ic.shape[1]+2, 1)).at[1:-1, 1:-1].set(ic.reshape(ic.shape[0], -1, 1))
	srt = jnp.zeros((srt.shape[0], srt.shape[1]+2, srt.shape[2]+2, srt.shape[3])).at[:, 1:-1, 1:-1, :].set(srt)
	ca.update.update_srt(srt=srt)
	assert num_steps <= srt.shape[0] or not strict, f"Requested time {num_steps} is out of bounds, max time {srt.shape[0]}"
	state_final, states = ca(state=state_init, time=time, num_steps=num_steps)
	states = jnp.concatenate([(state_init[1:-1, 1:-1].astype(int)).reshape(1, ic.shape[0], -1), (states[:, 1:-1, 1:-1].astype(int)).reshape(states.shape[0], ic.shape[0], -1)])
	return states
ic = jnp.array(
                [
                    [0, 0, 0, 0, 0, 0],
                    [0, 1, 1, 0, 0, 0],
                    [1, 0, 0, 1, 0, 0],
                    [0, 0, 1, 1, 0, 1],
                    [0, 1, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0],
                ]
            )
srt = jnp.array([[
		[[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		[[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		[[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		[[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		[[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		[[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		],[
		[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]],
		[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],
		]])
print(transition(ic, srt, 100000))

[[[0 0 0 0 0 0]
  [0 1 1 0 0 0]
  [1 0 0 1 0 0]
  [0 0 1 1 0 1]
  [0 1 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 1 1 1 0 0]
  [0 0 0 0 0 0]
  [0 1 1 0 0 0]
  [0 0 1 1 1 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 1 0 0 0]
  [0 0 0 0 0 1]
  [0 0 0 1 0 0]
  [0 0 0 0 1 0]
  [0 0 0 0 0 0]]

 ...

 [[0 0 0 0 0 0]
  [0 0 1 0 0 0]
  [0 0 0 0 0 1]
  [0 0 0 1 0 0]
  [0 0 0 0 1 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 1 0 0 0]
  [0 0 0 0 0 1]
  [0 0 0 1 0 0]
  [0 0 0 0 1 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 1 0 0 0]
  [0 0 0 0 0 1]
  [0 0 0 1 0 0]
  [0 0 0 0 1 0]
  [0 0 0 0 0 0]]]
